### ISSUE TITLE
Is it possible to.. reverse it? dif2obj?

### ISSUE THREAD

**Issue by zfbx** [HiGuyMB/obj2dif#2]
I know this project is a bit older and i don't know if you're still supporting it or not but is it possible to do the reverse of taking a .dif and making it an .obj or any other editable format?

**Comment by HiGuyMB** [comment]
Yep! See https://github.com/HiGuyMB/Dif/blob/master/tests/main.cpp#L107

**Comment by zfbx** [comment]
Thank you very much :)
